name: publish npm

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-workflow-passing-data:
    uses: Vioneta/github/.github/workflows/npm_release.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
